ZapConfig:
  Filename: "tmp/log"
  MaxSize: 5
  MaxAge: 400
  MaxBackups: 1000

DatabaseConfig:
  MysqlConfig:
    Username: "root"
    Password: "123456"
    Addr: "localhost:3306"
    DB: "Gocument"
  RedisConfig:
    Addr: "localhost:6379"
    Password: ""
    DB: 0

CosConfig:
  SecretId: AKIDra9XxGPeonZYLyb5i9NQGvMabO0RfgWQ
  SecretKey: rEST0vfEajfNwHRN8iBany31nLgnhT3Qc
  BucketnameAppid: lanshan-1338048877
  CosRegion: ap-chongqing